function cekKhodam() {
    const name = document.getElementById('name').value;
    const resultDiv = document.getElementById('result');

    if (name.trim() === '') {
        resultDiv.textContent = 'Harap masukkan nama!';
        return;
    }

    // Logika untuk menentukan hasil khodam, contoh sederhana
const khodams = [
    'Harimau',
    'Macan Putih',
    'Naga',
    'Singa',
    'Elang',
    'Alok',
    'Kak Gem',
    'Naruto',
    'Kyubi',
    'Gus Samsudin',
    'Garuda',
    'Kuda Sembrani',
    'Serigala',
    'Phoenix',
    'Raja Langit',
    'Putri Duyung',
    'Dewi Sri',
    'Hanoman',
    'Gatotkaca',
    'Bima',
    'Antareja',
    'Antasena',
    'Hiu',
    'Anjani',
    'Sakura',
    'Boboiboy',
    'Gopal',
    'Tidak Ada',
    'Yesus',
    'Iwan Bule',
    'Om Om Hitam',
    'Botak Hitam',
    'Ambatukam',
    'Raksasa',
    'Bidadari',
    'Asura',
    'Gareng',
    'Petruk',
    'Bagong',
    'Semar',
    'Punokawan',
    'Arjuna',
    'Nakula',
    'Sadewa',
    'Kresna',
    'Karna',
    'Satria Baja Hitam',
    'Tengkorak',
    'Kuntilanak',
    'Pocong',
    'Gendruwo',
    'Buto Ijo',
    'Wewe Gombel',
    'Nyi Roro Kidul',
    'Barong',
    'Rangda',
    'Ogoh-ogoh',
    'Taksaka',
    'Kera Sakti',
    'Sun Go Kong',
    'Dewi Kwan Im',
    'Jaka Tarub',
    'Dewi Lanjar',
    'Ratu Pantai Selatan',
    'Nyi Blorong',
    'Ratu Kidul',
    'Ande-Ande Lumut',
    'Timun Mas',
    'Kleting Kuning',
    'Panji Semirang',
    'Sangkuriang',
    'Dayang Sumbi',
    'Si Manis Jembatan Ancol',
    'Si Buta dari Gua Hantu',
    'Pitung',
    'Jampang',
    'Sabeni',
    'Wiro Sableng',
    'Pendekar 212',
    'Sinto Gendeng',
    'Gajah Mada',
    'Patih Gajah Mada',
    'Majapahit',
    'Raden Wijaya',
    'Ken Arok',
    'Ken Dedes',
    'Tunggul Ametung',
    'Airlangga',
    'Hayam Wuruk',
    'Tribhuana Tungga Dewi',
    'Roro Jonggrang',
    'Damarwulan',
    'Minak Jinggo',
    'Prabu Brawijaya',
    'Sultan Agung',
    'Diponegoro',
    'Teuku Umar',
    'Cut Nyak Dien',
    'Jembut Firaun',
    'Kapitan Pattimura'
];

    
    const randomIndex = Math.floor(Math.random() * khodams.length);
    const khodam = khodams[randomIndex];

    resultDiv.textContent = `Nama: ${name}, Khodam Anda adalah: ${khodam}`;
}
